# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 15:23
from __future__ import unicode_literals

import cms_named_menus.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('cms_named_menus', '0003_auto_20170928_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsnamedmenu',
            name='site',
            field=models.ForeignKey(default=cms_named_menus.models.get_current_site, help_text='The site the menu is accessible at.', on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='site'),
        ),
    ]
